---
project_name: vimbin
before:
  hooks:
    - go mod tidy
builds:
  - main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
dockers:
  - image_templates:
      - ghcr.io/containeroo/vimbin:{{ .Tag }}-amd64
    use: buildx
    dockerfile: Dockerfile
    extra_files:
      - go.mod
      - go.sum
      - main.go
      - cmd
      - internal
      - web
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/containeroo/vimbin
      - --label=org.opencontainers.image.source=https://github.com/containeroo/vimbin
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses="GNU General Public License v3.0"
  - image_templates:
      - ghcr.io/containeroo/vimbin:{{ .Tag }}-arm64
    use: buildx
    dockerfile: Dockerfile
    extra_files:
      - go.mod
      - go.sum
      - main.go
      - cmd
      - internal
      - web
    goarch: arm64
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/containeroo/vimbin
      - --label=org.opencontainers.image.source=https://github.com/containeroo/vimbin
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses="GNU General Public License v3.0"
docker_manifests:
  - name_template: ghcr.io/containeroo/vimbin:{{ .Tag }}
    image_templates:
      - ghcr.io/containeroo/vimbin:{{ .Tag }}-amd64
      - ghcr.io/containeroo/vimbin:{{ .Tag }}-arm64
  - name_template: ghcr.io/containeroo/vimbin:latest
    image_templates:
      - ghcr.io/containeroo/vimbin:{{ .Tag }}-amd64
      - ghcr.io/containeroo/vimbin:{{ .Tag }}-arm64
